tap "homebrew/bundle"
tap "homebrew/services"
tap "romkatv/powerlevel10k"

brew "cmake"
brew "curl"
brew "docker"
brew "htop"
brew "jq"
brew "powerlevel10k"
brew "watch"
brew "wget"
brew "mas"
brew "git"

cask "iTerm2"
cask "1password"
cask "1password-cli"
cask "jetbrains-toolbox"
cask "dropbox"
